general {
    lock_cmd = pidof hyprlock || hyprlock       # évite de lancer plusieurs instances de hyprlock.
    before_sleep_cmd = loginctl lock-session    # verrouille avant la mise en veille.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'  # rallume l'écran au réveil.
}

listener {
    timeout = 600                        # 10 min.
    on-timeout = loginctl lock-session   # verrouille l'écran après inactivité.
}

listener {
    timeout = 900                                                      # 15 min.
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "disable"})'   # éteint l'écran.
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'     # rallume au retour d'activité.
}

